title = "QualityDream Lab"
baseURL = "https://example.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Zhaohui Geng"
  description = "This is the research website of the QualityDream Lab at UTRGV."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = "/utrgv_logo.png"  # url or path to a logo to put in the header
  lablogo = "/lab_logo_2.PNG"
  [params.footer]
    text = "By Zhaohui Geng"
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "serif"
    pageWidth = "1000px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-google"
    title = "Google Scholar"
    url = "https://scholar.google.com/citations?user=iBFCNKUAAAAJ&hl=en&oi=ao"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/zhaohui-geng"
  [[params.socialIcons]]
    icon = "fab fa-researchgate"
    title = "ResearchGate"
    url = "https://www.researchgate.net/profile/Zhaohui-Geng"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/ZhaohuiGeng"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:zhg17@pitt.edu"
  

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/home"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/publication"
    weight = 3
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 4
  [[menu.main]]
    name = "Group"
    url = "/group"
    weight = 5



[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files